### ISSUE TITLE
tmt shared directory owned by first user who runs tmt

### ISSUE THREAD

**Issue by RHEmployee** [teemtee/tmt#537]
Reproducer:
under root run:
\# tmt run -vvvddd provision -h minute -i rhel-8 login finish

Then directory /var/tmp/tmt/ is created with:
rwxr-xr-x. 3 root root 21 Feb  9 04:59 /var/tmp/tmt/
then switch to normal user:
$ tmt run -vvvddd provision -h minute -i rhel-8 login finish
Failed to create workdir '/var/tmp/tmt/run-002' ([Errno 13] Permission denied: '/var/tmp/tmt/run-002')

**Comment by psss** [comment]
Relates to #356, perhaps it's a duplicate?

**Comment by RHEmployee** [comment]
Hi. I don't know.
Maybe this bug is just consequence of previous bug.

What do you think?

**Comment by lukaszachy** [comment]
It definitely relates to #356 and _might_ be fixed by its resolution.
However I'd leave this open until User story: 'tmt can be run on multiuser host' is possible.

**Comment by RHEmployee** [comment]
Hi. Do we have this solved by:
https://github.com/teemtee/tmt/pull/1119
?

So we can close this issue then?

However: https://github.com/teemtee/tmt/issues/356 is still open.

**Comment by lukaszachy** [comment]
This is still an issue
Also `file /var/tmp/tmt is not owned by any package` so packaging issue (should set ghost directory)

**Comment by RHEmployee** [comment]
Ok. Thans. it's multihost related so leaving it for now.
