### ISSUE TITLE
Discover from dist-git source should explore metadata under the source directory

### ISSUE THREAD

**Issue by psss** [teemtee/tmt#978]
Currently the source tarball is unpacked under the `discover/default/tests` directory and test discover is done from there. This brings two problems:

 * When the source tarball includes the `.fmf` directory it is ignored as a nested `fmf.Tree`.
 * Discovered tests names receive an extra prefix from the source directory

We should discover tests directly from the unpacked directory and make sure that it has metadata tree root defined, e.g. call `tmt init` if needed.

@martinpitt ran into this problem when working on this [cockpit pull request](https://src.fedoraproject.org/rpms/cockpit-machines/pull-request/4).

**Comment by lukaszachy** [comment]
Thank you for the report, I'll try to create a fix this week.
Proposal: Expectation is that extracted source contains .fmf root. When it is not there tmt will do `tmt init` in extracted sources.

New option `--dist-git-init` will change the behaviour:

- `False` -> disable feature (don't run tmt init at all), 
- `str` -> relative path in extracted sources where tmt init should be called, 
-  `True` -> call `tmt init` in the root of extracted sources [default]

**Comment by psss** [comment]
The `--dist-git-init` feature drafted above looks like a very elegant solution to me. Thanks!

**Comment by bcl** [comment]
I have a possibly separate problem with `dist-git-source`, I expected it to act like it did in the STI tests and extract the source and then run my test script, but it seems to be extracting the source, not finding any tests, and then not running the execute section. The test has already been found, that's what it is running, so why is execute skipped?

**Comment by lukaszachy** [comment]
> I expected it to act like it did in the STI tests and extract the source and then run my test script,

That is a bit different I'm afraid. In that case you are not expected to search for any tests in the extracted sources, right?
So dist-git-source just adds code but metadata are already present.
I think it could be quite easy to add.

**Comment by bcl** [comment]
I think I figured it out. The differences between plans and tests aren't obvious and I got it working by putting the actual test execution into tests/unit.fmf and the setup with dist-git-source into a corresponding plan under plans/

> In that case you are not expected to search for any tests in the extracted sources, right?

Right, the tmt tests are in dist-git.

**Comment by lukaszachy** [comment]
Needs more time to evaluate possible corner cases

**Comment by martinpitt** [comment]
Would it be possible to provide a solution for a single/first tarball, i.e. look at `Source0` only? The vast majority of packages have only one tarball anyway, and even more only have tests in their "primary" source tarball. We used to [have a hack in our cockpituous scripts](https://github.com/cockpit-project/cockpituous/commit/2ef3f6c9991), but with the world moving to packit (which does not have "nice" ways to arbitrarily hack files in dist-git) this becomes more awkward to work around.

**Comment by martinpitt** [comment]
For those following along, I created this hack and successfully tested it: https://github.com/cockpit-project/cockpit/pull/17378/files (but.. eww!)

**Comment by lukaszachy** [comment]
Could you try with #1128 please? I believe having more sources doesn't matter for that implementation.

**Comment by psss** [comment]
Should be covered by #1128.

**Comment by psss** [comment]
I've just pushed out bodhi updates. It should get to the Testing Farm around tomorrow.

**Comment by martinpitt** [comment]
Thanks @psss! We collided, I rebased https://src.fedoraproject.org/rpms/cockpit-machines/pull-request/4 an hour ago, and it [still failed](https://artifacts.dev.testing-farm.io/4d945886-b0d6-4755-a752-d7e7bdb5e402/). Nice! Then I'll retry with 1.14.0 once that lands.
